name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - mamba
  - jupyter
  - hda
  - ffmpeg
  - folium
  - pandas
  - lxml
  - matplotlib
  - hvplot
  - dask
  - datashader
  - geoviews
  - cartopy
  - dask
  - pyogrio
  - rioxarray
  - jupyter_bokeh
  - requests
  - statsmodels
  - aiohttp
  - zarr=2.18.4
  - mamba
  - matplotlib
  - numpy
  - odc
  - odc-geo
  - odc-stac
  - pandas
  - pip
  - pystac-client
  - rioxarray
  - scikit-learn
  - xarray
  - pip:
      - ascat
      - pdbufr
      - pynetcf
      - pre-commit
      - pyswi
