name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - python==3.11
  - cartopy
  - cmcrameri
  - dask
  - datashader
  - geoviews
  - hda
  - hvplot
  - jupyter
  - jupyter_bokeh
  - lxml
  - mamba
  - matplotlib
  - numpy
  - odc
  - odc-geo
  - odc-stac
  - pandas
  - pip
  - pystac-client
  - rioxarray
  - scikit-learn
  - xarray
  - pip:
      - ascat
      - pdbufr
      - pynetcf
      - python-dotenv
