name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - aiohttp
  - black
  - cartopy
  - dask
  - datashader
  - earthaccess
  - ffmpeg
  - fiona
  - flake8-nb
  - folium
  - geoviews
  - hda
  - hvplot
  - isort
  - jupyter
  - jupyter_bokeh
  - lxml
  - mamba
  - matplotlib
  - nbqa
  - openpyxl
  - pandas
  - pip
  - pyogrio
  - python=3.13
  - rasterio
  - requests
  - rioxarray
  - scikit-learn
  - statsmodels
  - zarr=2.18.4
  - pip:
      - ascat
      - pdbufr
      - python-dotenv
      - pynetcf
      - pre-commit
      - pyswi
