name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - mamba
  - jupyter
  - hda
  - pandas
  - lxml
  - matplotlib
  - hvplot
  - datashader
  - geoviews
  - cartopy
  - dask
  - jupyter_bokeh
  - rioxarray
  - xarray
  - pyjwt
  - netcdf4
  - cryptography
  - pip:
      - ascat
      - pdbufr
      - python-dotenv
      - pynetcf
