name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - black
  - earthaccess
  - ffmpeg
  - fiona
  - flake8-nb
  - folium
  - geoviews
  - hda
  - isort
  - importlib-metadata
  - nbqa
  - openpyxl
  - pyogrio
  - rioxarray
  - zarr=2.18.4
  - pip:
      - ascat
      - pdbufr
      - python-dotenv
      - pynetcf
      - pre-commit
      - pyswi
      - .
