name: environmental-remote-sensing
channels:
  - conda-forge
dependencies:
  - jupyter_bokeh
  - geoviews
  - mamba
  - lxml
  - matplotlib
  - pandas
  - cartopy
  - jupyter
  - hda
  - dask
  - datashader
  - hvplot
  - python=3.11
  - rioxarray
  - fiona
  - pyogrio
  - aiohttp
  - requests
  - zarr
  - earthaccess
  - rasterio
  - openpyxl
  - scikit-learn
  - pip:
      - ascat
      - pdbufr
      - python-dotenv
      - pynetcf
      - pre-commit
      - pyswi

